# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'skrudzh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for skrudzh
  pod 'Swinject', '2.5'
  pod 'SwinjectStoryboard', '2.1'
  pod 'Locksmith', '~> 4.0'
  pod 'PromiseKit', '~> 6.5'
  pod 'PromiseKit/Alamofire', '~> 6.5'
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'AlamofireImage'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'SwiftDate', '~> 5.0'
  pod 'SwifterSwift', '~> 4.6'
  pod 'CWStatusBarNotification', '~> 2.3'
  pod 'SideMenu'
end
