# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'skrudzh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for skrudzh
  pod 'Swinject', '2.6.0'
  pod 'SwinjectStoryboard', '2.1'
  pod 'SwinjectAutoregistration', '2.6.0'
  pod 'Locksmith', '~> 4.0'
  pod 'PromiseKit', '~> 6.5'
  pod 'PromiseKit/Alamofire', '~> 6.5'
  pod 'IQKeyboardManager'
  pod 'AlamofireImage'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'SwiftDate', '~> 5.0'
  pod 'SwifterSwift', '~> 4.6'
  pod 'CWStatusBarNotification', '~> 2.3'
  pod 'SideMenu'
  pod 'StaticDataTableViewController'
  pod 'SwiftMessages'
  pod 'SkyFloatingLabelTextField'
  pod 'CircleProgressView', '~> 1.0'
  pod 'BEMCheckBox'
  pod 'AlignedCollectionViewFlowLayout'
  pod 'ALTextInputBar', git: 'https://github.com/bclymer/ALTextInputBar', branch: 'master'
  pod 'Charts'
  pod 'RandomColorSwift'
  pod 'MSPeekCollectionViewDelegateImplementation'
  pod 'CSV.swift'
  pod 'RecurrencePicker'
end
